learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('', include(('logs.urls', 'logs'), namespace='logs')),
]

logs/urls.py
from django.urls import path
from logs import views
from django.conf import settings

app_name = "logs"

urlpatterns = [
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('resources/', views.resources, name='resources'),
    path('new_topic/', views.new_topic, name="new_topic"),
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    path('topic/<int:topic_id>/', views.topic, name='topic'),
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
    path('edit_topic/<int:topic_id>/', views.edit_topic, name='edit_topic'),
    path('delete_entry/<int:entry_id>/', views.delete_entry, name='delete_entry'),
    path('delete_topic/<int:topic_id>/', views.delete_topic, name='delete_topic'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name="login"),
    path('logout/', LogoutView.as_view(template_name='index.html'), name="logout"),
    # Registration Page
    path('register/', views.register, name='register'),
]

logs/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Topic(models.Model):
    title = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, default=None, null=True, blank=True)

    def __str__(self):
        return self.title


class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)
    text = models.TextField()

    class Meta:
        verbose_name_plural="Entries"

    def __str__(self):
        return f"{self.text[:50]}..."


class Link(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)
    link = models.TextField()
    comment = models.TextField()

    def __str__(self):
        if len(self.link)<= 100:
            return f"{self.link[:100]}"
        else:
            return f"{self.link[:100]}..."

logs/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model  = Topic
        fields = ['title']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model   = Entry
        fields  = ['text']
        lables  = {'text':''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}
        # customes the input widget for field "text", default is 40


class DeleteEntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = []


class DeleteTopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = []

logs/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Topic, Entry, Link
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import TopicForm, EntryForm, DeleteEntryForm, DeleteTopicForm
from django.contrib.auth.decorators import login_required
# Create your views here.


def index(request):
    t = Topic.objects.order_by("title")
    context = {'topics':t}
    return render(request, "index.html", context)
    #return HttpResponse("<h1>Hello Django</h1>")


@login_required
def topics(request):
    t = Topic.objects.filter(owner=request.user).order_by("title")
    context = {"topics": t}
    return render(request, "topics.html", context)


def resources(request):
    topics = Topic.objects.all()
    topics_links = {}
    for t in topics:
        links = t.link_set.all()
        topics_links[t] = links
    context = {"topics":topics_links} # topics_links ={topic1: links, topic2: links....}

    return render(request, "resources.html", context)


@login_required
def topic(request, topic_id):
    '''show a single topic and all its entries'''
    topic = Topic.objects.filter(owner=request.user).get(id=topic_id)
    entries = topic.entry_set.order_by('date_added')
    context = {"topic": topic, "entries": entries}
    return render(request,"topic.html", context)


@login_required
def new_topic(request):
    '''Add a new topic'''

    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(request.POST, request.user)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('logs:topics'))
    context = {'form': form}
    return render(request, 'new_topic.html', context)


@login_required
def edit_topic(request, topic_id):
    '''Edit a new topic'''
    topic = Topic.objects.get(id = topic_id)
    num = len(topic.entry_set.all()) # number of entries under this topic
    if request.method != 'POST':
        form = TopicForm(instance = topic)
    else:
        form = TopicForm(instance=topic, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("logs:topic", args=[topic.id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'edit_topic.html', context)


@login_required
def new_entry(request, topic_id):
    '''Add a new entry for a particular topic'''
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data = request.POST)
        if form.is_valid():
            new_entry=form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('logs:topic', args=[topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    '''Edit an existing entry.'''
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance =entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('logs:topic', args=[topic.id]))
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'edit_entry.html', context)


@login_required
def delete_entry(request, entry_id):
    '''delete an existng entry.'''
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    entry_to_delete = get_object_or_404(Entry, id=entry_id)

    if request.method!='POST':
        form = DeleteEntryForm(instance=entry)
    else:
        form = DeleteEntryForm(instance=entry,data=request.POST)
        if form.is_valid():
            entry_to_delete.delete()
            return HttpResponseRedirect(reverse('logs:topic', args=[topic.id]))
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'delete_entry.html', context)


@login_required
def delete_topic(request, topic_id):
    '''delete an existng topic.'''
    topic = Topic.objects.get(id=topic_id)
    topic_to_delete = get_object_or_404(Topic, id=topic_id)
    if request.method != 'POST':
        form = DeleteTopicForm(instance=topic)
    else:
        form = DeleteTopicForm(instance=topic, data=request.POST)
        if form.is_valid():
            topic_to_delete.delete()
            return HttpResponseRedirect(reverse('logs:topics'))
    context = {'topic': topic, 'form': form}
    return render(request, 'delete_topic.html', context)

logs/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- responsive -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- [/] responsive -->
    <title>Learning Logs</title>
    <link rel="shortcut icon" href="static/favicon_ming.ico">

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>


  <style>
  /* Make the image fully responsive */
  .carousel-inner img {
    width: 100%;
    height: 100%;
  }

    {% load static %}

  </style>

</head>
<body>

    <!--<img src="{% static 'DJI_0268.jpg' %}" alt="Nusa Penida",  style="width:1100px; height:200px">-->
    <br>
     <div class="container">
	    <div id="demo" class="carousel slide" data-ride="carousel">
	      <ul class="carousel-indicators">
	        <li data-target="#demo" data-slide-to="0" class="active"></li>
	        <li data-target="#demo" data-slide-to="1"></li>
	        <li data-target="#demo" data-slide-to="2"></li>
	      </ul>
	      <div class="carousel-inner">
	        <div class="carousel-item active">
	          <img  src="{% static 'penida.jpg' %}" alt="Nusa Penida" width="1100" height="500">
	          <div class="carousel-caption">
	            <h3>Nusa Penida</h3>
	            <p>We had such a great time in Penida!</p>
	          </div>
	        </div>
	        <div class="carousel-item">
	          <img src="{% static 'sunset.jpg' %}" alt="Sunset Outpost" width="1100" height="500">
	          <div class="carousel-caption">
	            <h3>Sunset</h3>
	            <p>Thank you, Outpost!</p>
	          </div>
	        </div>
	        <div class="carousel-item">
	          <img src="{% static 'ricefield.jpg' %}" alt="Rice Field" width="1100" height="500">
	          <div class="carousel-caption">
	            <h3>Rice Field</h3>
	            <p>We love Ubud!</p>
	          </div>
	        </div>
	      </div>
	      <a class="carousel-control-prev" href="#demo" data-slide="prev">
	        <span class="carousel-control-prev-icon"></span>
	      </a>
	      <a class="carousel-control-next" href="#demo" data-slide="next">
	        <span class="carousel-control-next-icon"></span>
	      </a>
	    </div>

    <h2>Learning log - Bali 2019</h2>

    <div class = "bs-component">
      <ul class="nav nav-tabs ">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logs:index' %}">Index</a>
        </li>

        <li class="nav-item">
          <!--<a class="nav-link active" data-toggle="tab" href="{% url 'logs:topics' %}">Topics</a>-->
            <a  class="nav-link" href="{% url 'logs:topics' %}">Topics</a>
        </li>
        <li class="nav-item">

          <a class="nav-link"  href="{% url 'logs:resources' %}">Links</a>
        </li>
      </ul>
           <ul class="nav justify-content-end">

                     {% if user.is_authenticated %}
                      <li class="nav-item">
                          <a class="nav-link active" href="{% url 'users:logout' %}">Log out</a>
                      </li>

                      <li class="nav-item">
                          <a class="nav-link active" data-toggle="tab" color="black" ><strong>Hello, {{user.username}}!</strong></a>
                      </li>

                      {% else %}
                      <li class="nav-item" >
                          <a class="nav-link active" href="{% url 'users:register' %}">Register</a>
                      </li>

                      <li class="nav-item" >
                          <a class="nav-link active" href="{% url 'users:login' %}">Log in</a>
                      </li>
                      {% endif %}
             </ul>

    </div>



        <div class = "alert alert-dismissible alert-info" align="left">
            During this 8-week bookcamp, we have learned from internet, lectures, activities, each other
            and above all from our own mistakes. This is the learning log not only for Python and web development.
            It's a space for learning. Keep a record of what you learned today. Starting now!
        </div>


    </div>

    <div class="container">
        {% block content %}

        {% endblock%}
    </div>

    <br>

    <div class="container">
        {% block footer%}
             <foot>Copyright @2019 MingY</foot>
        {% endblock%}
    </div>


</body>
</html>

logs/templates/delete_entry.html
{% extends "base.html" %}

{% block content %}
    <p><a href="{% url 'logs:topic' topic.id %}">{{ topic }}</a></p>

    <h5>Are you sure you want to delete this entry?</h5>
    <br>
    <form action="{% url 'logs:delete_entry' entry.id %}" method='post'>
    {% csrf_token%}
    {{form.as_p}}
    <button name = "submit">Yes, delete!</button>

    </form>

{% endblock %}

logs/templates/delete_topic.html
{% extends "base.html" %}

{% block content %}
    <p><a href="{% url 'logs:topic' topic.id %}">{{ topic }}</a></p>

    <h5>Are you sure you want to delete this topic and all the entries inside?</h5>
    <br>
    <form action="{% url 'logs:delete_topic' topic.id %}" method='post'>
    {% csrf_token%}
    {{form.as_p}}
    <button name = "submit">Yes, delete!</button>

    </form>

{% endblock %}

logs/templates/edit_entry.html
{% extends "base.html" %}

{% block content %}
    <p><a href="{% url 'logs:topic' topic.id %}">{{ topic }}</a></p>

    <h4>Edit entry:</h4>
    <form action="{% url 'logs:edit_entry' entry.id %}" method='post'>
    {% csrf_token%}
    {{form.as_p}}
    <button name = "submit">Save changes</button>

    </form>

{% endblock %}

logs/templates/edit_topic.html
{% extends "base.html" %}

{% block content %}
    <p><a href="{% url 'logs:topic' topic.id %}">{{ topic }}</a></p>

    <h4>Edit Topic:</h4>
    <form action="{% url 'logs:edit_topic' topic.id %}" method='post'>
    {% csrf_token%}
    {{form.as_p}}
    <button name = "submit">Save changes</button>

    </form>

{% endblock %}

logs/templates/home.html
{% extends "base.html"%}

    {% block content %}
        <h3>Structure of this site</h3>
        <ul>
            <li>Current page - Index</li>
            <li><a href="{% url 'logs:topics' %}">List of Topics</a></li>
            <li>Add New Topics</li>
            <li>Add New Entries</li>
            <li><a href="{% url 'logs:resources' %}">List of Useful Links</a></li>
        </ul>

    {% endblock%}

logs/templates/index.html
{% extends "base.html"%}

    {% block content %}
        <h3>Welcome to the world of knowledge!</h3>
        <p>Here is what you can do here. Please note that this site is still under construction. Do come back for more
        later on.... Thank you!</p>
        <ul>
            <li>Register an account with a username and password</li>
            <li>Log in to your account if you have one</li>
            <li>Going to the <a href="{% url 'logs:topics' %}">List of Topics</a></li>
            <li>You can enter topics of your choice</li>
            <li>And add entries under your topics</li>
            <li>Here are some useful <a href="{% url 'logs:resources' %}">Links</a> here too.</li>

        </ul>

        <span class="badge badge-info">User experience is very important. Please send me your feedback.</span>
        <br>

    {% endblock%}

logs/templates/new_entry.html
{% extends "base.html" %}

{% block content %}
    <p><a href="{% url 'logs:topic' topic.id %}">{{ topic }}</a></p>

    <h4>Add a new entry here:</h4>
    <form action="{% url 'logs:new_entry' topic.id %}" method='post'>
    {% csrf_token%}
    {{form.as_p}}
    <button name = "submit">Add Entry</button>

    </form>

{% endblock %}

logs/templates/new_topic.html
{% extends "base.html" %}

{% block content %}
    <h4>Add a new topic here:</h4>
    <form action="{% url 'logs:new_topic' %}" method='post'>
    {% csrf_token%}
    {{form.as_p}}
    <button name = "submit">Add Topic</button>

    </form>

{% endblock %}

logs/templates/resources.html
{% extends "base.html"%}

    {% block content %}
        <h3>List of Useful links</h3>

        <ol>
            {% for topic, links in topics.items %}
                {% for link in links %}
                    <li>{{topic}}
                         <ul>
                            <li><a href="{{ link }}">{{link}}</a></li>
                        </ul>
                    </li>
                {% empty %}
                <!--<li>No link yet for this topic.</li>-->
                {% endfor %}
            {% endfor %}
        </ol>

    {% endblock%}

logs/templates/topic.html
{% extends "base.html"%}

    {% block content %}
        <p>Topic: {{topic}}                         -
            <a href="{% url 'logs:edit_topic' topic.id %}">Edit Topic</a>
                  -
            <a href="{% url 'logs:delete_topic' topic.id %}">Delete Topic</a>
        </p>
        <p>Entries:</p>
        <p><a href="{% url 'logs:new_entry' topic.id %}">Add New Entry</a></p>
        <ul>
            {% for entry in entries%}
                <li>
                    <p>{{ entry.date_added|date:"Y-m-d, H:i:s"}}</p>
                    <p>{{ entry.text|linebreaks}}</p>
                    <p>
                        <a href="{% url 'logs:edit_entry' entry.id %}">Edit Entry</a>
                         -
                        <a href="{% url 'logs:delete_entry' entry.id %}">Delete Entry</a>
                    </p>
                </li>
            {% empty%}
                <li>
                    There are no entries for this topic yet.

                </li>
            {% endfor %}
        </ul>


    {% endblock%}

logs/templates/topics.html
{% extends "base.html"%}

    {% block content %}
        <button name = "Add new topic"><a href="{% url 'logs:new_topic' %}">Add New Topic</a></button>
        <br><br>

        <h4>List of Topics</h4>
        <ol>
            {% for topic in topics %}
            <li>
                <a href="{% url 'logs:topic' topic.id %}">{{ topic }}</a>
            </li>
            {% endfor %}

        </ol>

<!---->
    {% endblock%}